[package]
name = "attr-bounds"
version = "0.1.0"
edition = "2021"
authors = ["Mitsuharu Okuno"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = { version = "2.0.66", features = ["full"] }

[dev-dependencies]
trybuild = "1.0.96"
